# Link MongoDB and API
version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    hostname: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mmh
      - MONGO_INITDB_ROOT_PASSWORD=3L1$$y&Um!
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/MongoDB
    logging:
      driver: "none"

  api:
    container_name: api
    hostname: api
    build: .
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_URI=mongodb://192.168.1.21:27017/mmh?retryWrites=true
      - JWT_SECRET=theblueknightisfollowedbythecrinsomsun
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb

# Exec -> docker compose build -> docker compose up

# Directorio para MongoDB -> Es mejor crerarlo que no dar un path
volumes:
  mongodb: {}
